### ISSUE TITLE
Unable to reject points on web app when searching by point type or name

### ISSUE THREAD

**Issue by cutler4** [PurdueHCR/Firestore#84]
Whenever RHPs try to reject points on the web app when searching by point type or resident name, the point does not get rejected. The box asking for the reason will appear and the buttons work but it does not actually reject the point.

**Comment by Decoder22** [comment]
@cutler4 Can you provide more details for this? I am not able to replicate this bug using an RHP account, clicking on house history, then searching for a resident by last name. I see that the point type is updating as rejected and house points are being updated accordingly
